### PR TITLE
allow empty dsn

### PR DESCRIPTION
**Pull request by RemiDesgrange**
This way, you can pass `SENTRY_DSN` as env var.

Can you point out where the test should be modified ?

### CODE REVIEW

**Comment by serathius** [comment]
I don't understand argument for allowing empty dsn. 
Example:
```
app = Sanic(__name__)
app.config['SENTRY_DSN'] = os.environ.get('SENTRY_DSN', None)
if app.config['SENTRY_DSN'] is not None:
    plugin = SanicSentry(app)
```

This way user needs to explicitly show that he wants to silence problem. 
You could argue that we should disable plugin if `None` is passed, but that's different.

**Comment by RemiDesgrange** [comment]
With my code, If no `SENTRY_DSN` is found, then `raven.Client` will try to fetch `SENTRY_DSN`  from env var. If no `SENTRY_DSN` is found, then raven is disabled. see https://github.com/getsentry/raven-python/blob/master/raven/base.py#L131-L142

**Comment by serathius** [comment]
Tests are based on tox + pytest, and can be found in `tests.py`
Running (need to add this to readme)
```bash
pip install tox
tox
```

**Comment by serathius** [comment]
Looks like there is problem with dependencies in CI, I will fix them myself.
Please update README to reflect your changes, describing that parameter is no longer required and what effect it has (using environment variable).

**Comment by RemiDesgrange** [comment]
Let me now if it's ok for you, and I'll squash before merging.

**Comment by serathius** [comment]
Tests should be fixed on master, you can cherry pick.
As for README: 
* You can move `SENTRY_DSN - Sentry DSN for your application` from under Usage header to replace `SENTRY_DSN is not mandatory`
* As SENTRY_DSN is now optional we can move `Optional parameters` up
* We can simplify explanation of process by writing something like "SENTRY_DSN - Sentry DSN for your application. If not set raven will fallback to `SENTRY_DSN` environment variable. Not setting either will disable raven."

What do you think? Can you fix it?

**Comment by serathius** [comment]
thanks

**Pull request merged**
